### ISSUE TITLE
fb-messenger does not answer

### ISSUE THREAD

**Issue by Availleight** [QuentinCG/jarvis-fb-messenger#9]
Hi, I'm writting this post because I need help for the messenger plugin.
When I launch jarvis, log shows me that messenger is connected and with my pricipal account, it shows me that jarvis has readen the message but it doesn't answer to it.

Could you help me please?

**Comment by QuentinCG** [comment]
Could you paste the logs here please ;)

**Comment by Availleight** [comment]
enzo@enzo-desktop:~/jarvis$ ./jarvis.sh
ln: impossible de créer le lien symbolique '/usr/local/bin/jarvis': Le fichier existe

------------ Config ------------
jv_branch            beta 
jv_version            
jv_arch              x86_64 
jv_os_name           ubuntu 
jv_os_version        16.04 
language             fr_FR 
play_hw              false 
rec_hw                
speaker              Default 
microphone           Default 
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.0.21:8080
Starting Facebook messenger-Jarvis server with user 'enzovaleur@hotmail.fr'
Starting User Interface on http://192.168.0.21:8081
DEBUG:root:Initializing Facebook messenger server with email 'enzovaleur@hotmail.fr', getId='False', verbose='True',  mute='True', allowAll='True' and allowedList='['100010043825538', 'id_2_here', 'id_3_here', '...']'.
Logging in enzovaleur@hotmail.fr...
INFO:client:Logging in enzovaleur@hotmail.fr...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=1&seq=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET /?__req=3&seq=0 HTTP/1.1" 200 None
Login of enzovaleur@hotmail.fr successful.
INFO:client:Login of enzovaleur@hotmail.fr successful.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=4&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&seq=0&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 75
Listening...
INFO:client:Listening...
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=5&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=0&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=6&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=0&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 123
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=7&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=1&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=8&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=1&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 187
DEBUG:client:Chat Timestamps received: {'100010043825538': 1506534303}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=9&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=2&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
192.168.0.21 - - [27/Sep/2017 19:45:21] "POST / HTTP/1.1" 200 -
192.168.0.21 - - [27/Sep/2017 19:45:21] "POST / HTTP/1.1" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.21', 55504)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
DEBUG: start_speaking hook
Jarvis: Hello
utils/utils.sh: ligne 172: svox_pico_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*HELP*						*WHAT*YOUR*NAME*
*WHAT*MY*NAME*		*SAY*HELLO*MOM*		*SAY*HELLO*DAD*
*THANKS*		*BYE*			*CANCEL*|*STOP*
*ENCORE*		*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*HELLO*|*HI*		>*YES*
>>*YES*			>>*NO*			>*NO*
>>*YES*			>>*NO*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

Commands from plugin jarvis-fb-messenger:
*ENVOI*MESSAGE*FACEBOOK
enzo: DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=a&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=2&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 154
DEBUG:client:Unknown message received: {'st': 1, 'from': 100010043825538, 'type': 'typ', 'to': 100022300173279, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=b&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=3&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=c&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=3&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 155
DEBUG:client:Unknown message received: {'st': 0, 'from': 100010043825538, 'type': 'typ', 'to': 100022300173279, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=d&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=4&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=e&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=4&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 402
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/delivery_receipts.php HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/change_read_status.php HTTP/1.1" 200 None
DEBUG:root:Received message from '100010043825538': 'Hi'.
DEBUG:root:Sending command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' to Jarvis.
python: can't open file '/home/enzo/Jarvis/jarviscli/': [Errno 2] No such file or directory
Exception in parsing of {'queue': 100022300173279, 'ofd_ts': 1506534325860, 'iseq': 106, 'type': 'delta', 'delta': {'body': 'Hi', 'class': 'NewMessage', 'irisSeqId': '106', 'messageMetadata': {'timestamp': '1506534325738', 'offlineThreadingId': '6318862950149679314', 'tags': ['source:chat:orca'], 'threadKey': {'otherUserFbId': '100010043825538'}, 'messageId': 'mid.$cAAAADSaJPl1k9bbF6lexHF_YDGjS', 'actorFbId': '100010043825538'}, 'attachments': []}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
ERROR:client:Exception in parsing of {'queue': 100022300173279, 'ofd_ts': 1506534325860, 'iseq': 106, 'type': 'delta', 'delta': {'body': 'Hi', 'class': 'NewMessage', 'irisSeqId': '106', 'messageMetadata': {'timestamp': '1506534325738', 'offlineThreadingId': '6318862950149679314', 'tags': ['source:chat:orca'], 'threadKey': {'otherUserFbId': '100010043825538'}, 'messageId': 'mid.$cAAAADSaJPl1k9bbF6lexHF_YDGjS', 'actorFbId': '100010043825538'}, 'attachments': []}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
Inbox event: 1, 1, 1
INFO:client:Inbox event: 1, 1, 1
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=h&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=7&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=i&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=7&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 197
DEBUG:client:Unknown message received: {'queue': 100022300173279, 'ofd_ts': 1506534326688, 'iseq': 107, 'type': 'delta', 'delta': {'class': 'MarkUnread', 'irisSeqId': '107', 'threadKeys': [{'otherUserFbId': '100010043825538'}]}}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=j&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=8&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=k&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=8&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 154
DEBUG:client:Unknown message received: {'st': 1, 'from': 100010043825538, 'type': 'typ', 'to': 100022300173279, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=l&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=9&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=m&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=9&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 153
DEBUG:client:Unknown message received: {'st': 0, 'from': 100010043825538, 'type': 'typ', 'to': 100022300173279, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=n&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=10&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=o&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=10&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 379
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/delivery_receipts.php HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/change_read_status.php HTTP/1.1" 200 None
DEBUG:root:Received message from '100010043825538': 'Hi'.
DEBUG:root:Sending command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' to Jarvis.
python: can't open file '/home/enzo/Jarvis/jarviscli/': [Errno 2] No such file or directory
Exception in parsing of {'queue': 100022300173279, 'ofd_ts': 1506534334524, 'iseq': 108, 'type': 'delta', 'delta': {'body': 'Hi', 'class': 'NewMessage', 'irisSeqId': '108', 'messageMetadata': {'timestamp': '1506534334452', 'offlineThreadingId': '6318862986741676812', 'tags': ['source:chat:orca'], 'threadKey': {'otherUserFbId': '100010043825538'}, 'messageId': 'mid.$cAAAADSaJPl1k9bbn9FexHGhdGfsM', 'actorFbId': '100010043825538'}, 'attachments': []}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
ERROR:client:Exception in parsing of {'queue': 100022300173279, 'ofd_ts': 1506534334524, 'iseq': 108, 'type': 'delta', 'delta': {'body': 'Hi', 'class': 'NewMessage', 'irisSeqId': '108', 'messageMetadata': {'timestamp': '1506534334452', 'offlineThreadingId': '6318862986741676812', 'tags': ['source:chat:orca'], 'threadKey': {'otherUserFbId': '100010043825538'}, 'messageId': 'mid.$cAAAADSaJPl1k9bbn9FexHGhdGfsM', 'actorFbId': '100010043825538'}, 'attachments': []}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
Inbox event: 1, 1, 1
INFO:client:Inbox event: 1, 1, 1
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=r&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=12&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?__req=s&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&msgs_recv=0&sticky_pool=atn1c09_chat-proxy&seq=12&sticky_token=340&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 197
DEBUG:client:Unknown message received: {'queue': 100022300173279, 'ofd_ts': 1506534335417, 'iseq': 109, 'type': 'delta', 'delta': {'class': 'MarkUnread', 'irisSeqId': '109', 'threadKeys': [{'otherUserFbId': '100010043825538'}]}}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?__req=t&ttstamp=658171521096611471977910710858658172865181567152116110562&__user=100022300173279&clientid=59dcb521&__rev=3328987&__a=1&partition=-2&cap=0&uid=100022300173279&seq=13&sticky_pool=atn1c09_chat-proxy&viewer_uid=100022300173279&sticky_token=340&state=active&channel=p_100022300173279&fb_dtsg=AQG4mBrGaOkl%3AAQHV3Q8G4tn8 HTTP/1.1" 200 22

**Comment by QuentinCG** [comment]
> DEBUG:root:Sending command '['jarvis', '-j', '-m', '-v', '-x', 'Hi']' to Jarvis.
python: can't open file '/home/enzo/Jarvis/jarviscli/': [Errno 2] No such file or directory

Strange...
Can you try to launch your Jarvis and send this command from an other shell from an other directory than jarvis folder: "`jarvis -j -m -v -x "Hi"`
If it doesn't work, something is wrong with your Jarvis (but not a big deal).
This is maybe due to this:
> ln: impossible de créer le lien symbolique '/usr/local/bin/jarvis': Le fichier existe

To fix the issue (even if it's ugly since your jarvis should be fixed): edit the plugin file script/facebook_server.py line 26:
 replace `self.program = ["jarvis", "-j"]` by `self.program = ["{PATH TO JARVIS FOLDER}/jarvis.sh", "-j"]` (example: `self.program = ["/home/me/jarvis/jarvis.sh", "-j"]`)

Other solution which would be better since it would fix your jarvis: execute command `sudo rm /usr/local/bin/jarvis`

**Comment by Availleight** [comment]
Some things work now like the launch by jarvis command or the GUI that recognize the commands but jarvis still doesn't answer me on messenger, even with your instructions.

**Comment by QuentinCG** [comment]
Can you paste the log again with the fix you added?

**Comment by Availleight** [comment]
enzo@enzo-desktop:~$ jarvis

------------ Config ------------
jv_branch            beta 
jv_version            
jv_arch              x86_64 
jv_os_name           ubuntu 
jv_os_version        16.04 
language             fr_FR 
play_hw              false 
rec_hw                
speaker              Default 
microphone           Default 
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

No mic configured, forcing keyboard mode
DEBUG: program_startup hook
Starting RestAPI server on http://192.168.0.21:8080
Starting Facebook messenger-Jarvis server with user 'enzovaleur@hotmail.fr'
Starting User Interface on http://192.168.0.21:8081
DEBUG:root:Initializing Facebook messenger server with email 'enzovaleur@hotmail.fr', getId='False', verbose='True',  mute='True', allowAll='False' and allowedList='['100010043825538', 'id_2_here', 'id_3_here', '...']'.
Logging in enzovaleur@hotmail.fr...
INFO:client:Logging in enzovaleur@hotmail.fr...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?seq=0&__req=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
192.168.0.21 - - [27/Sep/2017 20:53:16] "POST / HTTP/1.1" 200 -
192.168.0.21 - - [27/Sep/2017 20:53:16] "POST / HTTP/1.1" 400 -
----------------------------------------
Exception happened during processing of request from ('192.168.0.21', 37020)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
DEBUG: start_speaking hook
Jarvis: Hello
utils/utils.sh: ligne 172: svox_pico_TTS : commande introuvable
DEBUG: stop_speaking hook
User defined commands:
*HELP*						*WHAT*YOUR*NAME*
*WHAT*MY*NAME*		*SAY*HELLO*MOM*		*SAY*HELLO*DAD*
*THANKS*		*BYE*			*CANCEL*|*STOP*
*ENCORE*		*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*		*HELLO*|*HI*		>*YES*
>>*YES*			>>*NO*			>*NO*
>>*YES*			>>*NO*
Commands from plugin jarvis-ui:
*OUVR*INTERFACE*
Commands from plugin jarvis-api:

Commands from plugin jarvis-fb-messenger:
*ENVOI*MESSAGE*FACEBOOK
enzo: DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET /?seq=0&__req=3 HTTP/1.1" 200 None
Login of enzovaleur@hotmail.fr successful.
INFO:client:Login of enzovaleur@hotmail.fr successful.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 0-edge-chat.facebook.com
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?channel=p_100022300173279&clientid=6c151adc&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=0&__rev=3328987&msgs_recv=0&__req=4 HTTP/1.1" 200 75
Listening...
INFO:client:Listening...
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=0&__rev=3328987&state=active&__req=5&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=0&__rev=3328987&msgs_recv=0&__req=6&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 123
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=1&__rev=3328987&state=active&__req=7&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=1&__rev=3328987&msgs_recv=0&__req=8&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 186
DEBUG:client:Chat Timestamps received: {'100010043825538': 1506538376}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=2&__rev=3328987&state=active&__req=9&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=2&__rev=3328987&msgs_recv=0&__req=a&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 169
DEBUG:client:Unknown message received: {'device_id': '950e76b8-412d-4f45-9650-d4467e3375b6', 'from': 100010043825538, 'st': 1, 'type': 't_tp', 'app_id': '256002347743983'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=3&__rev=3328987&state=active&__req=b&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=3&__rev=3328987&msgs_recv=0&__req=c&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 169
DEBUG:client:Unknown message received: {'device_id': '950e76b8-412d-4f45-9650-d4467e3375b6', 'from': 100010043825538, 'st': 0, 'type': 't_tp', 'app_id': '256002347743983'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=4&__rev=3328987&state=active&__req=d&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=4&__rev=3328987&msgs_recv=0&__req=e&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 169
DEBUG:client:Unknown message received: {'device_id': '950e76b8-412d-4f45-9650-d4467e3375b6', 'from': 100010043825538, 'st': 1, 'type': 't_tp', 'app_id': '256002347743983'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=5&__rev=3328987&state=active&__req=f&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=5&__rev=3328987&msgs_recv=0&__req=g&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 155
DEBUG:client:Unknown message received: {'st': 1, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True, 'to': 100022300173279, 'from': 100010043825538, 'type': 'typ'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=6&__rev=3328987&state=active&__req=h&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=6&__rev=3328987&msgs_recv=0&__req=i&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 154
DEBUG:client:Unknown message received: {'st': 0, 'realtime_viewer_fbid': 100022300173279, 'from_mobile': True, 'to': 100022300173279, 'from': 100010043825538, 'type': 'typ'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=7&__rev=3328987&state=active&__req=j&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=7&__rev=3328987&msgs_recv=0&__req=k&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 401
Inbox event: 1, 1, 1
INFO:client:Inbox event: 1, 1, 1
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/delivery_receipts.php HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "POST /ajax/mercury/change_read_status.php HTTP/1.1" 200 None
DEBUG:root:Received message from '100010043825538': 'Help'.
DEBUG:root:Sending command '['/home/enzo/jarvis.sh', '-j', '-m', '-v', '-x', 'Help']' to Jarvis.
Exception in parsing of {'ofd_ts': 1506538417649, 'queue': 100022300173279, 'type': 'delta', 'iseq': 139, 'delta': {'irisSeqId': '139', 'class': 'NewMessage', 'messageMetadata': {'offlineThreadingId': '6318880110984828769', 'actorFbId': '100010043825538', 'messageId': 'mid.$cAAAADSaJPl1k9fU1dFexK_tpiBdh', 'tags': ['source:chat:orca'], 'timestamp': '1506538417524', 'threadKey': {'otherUserFbId': '100010043825538'}}, 'attachments': [], 'body': 'Help'}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/enzo/jarvis.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
ERROR:client:Exception in parsing of {'ofd_ts': 1506538417649, 'queue': 100022300173279, 'type': 'delta', 'iseq': 139, 'delta': {'irisSeqId': '139', 'class': 'NewMessage', 'messageMetadata': {'offlineThreadingId': '6318880110984828769', 'actorFbId': '100010043825538', 'messageId': 'mid.$cAAAADSaJPl1k9fU1dFexK_tpiBdh', 'tags': ['source:chat:orca'], 'timestamp': '1506538417524', 'threadKey': {'otherUserFbId': '100010043825538'}}, 'attachments': [], 'body': 'Help'}}
Traceback (most recent call last):
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 50, in _exec
    output = check_output(command)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/home/enzo/jarvis.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1412, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 99, in onMessage
    response = self.executeOrder(str(message))
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 64, in executeOrder
    result_from_request = self._exec([str("-x"), str(phrase)]).decode('utf-8')
  File "/home/enzo/jarvis/plugins_enabled/jarvis-fb-messenger/script/facebook_server.py", line 51, in _exec
    except CalledProcessError:
NameError: name 'CalledProcessError' is not defined
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=10&__rev=3328987&state=active&__req=n&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=10&__rev=3328987&msgs_recv=0&__req=o&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 197
DEBUG:client:Unknown message received: {'ofd_ts': 1506538419056, 'queue': 100022300173279, 'type': 'delta', 'iseq': 140, 'delta': {'irisSeqId': '140', 'class': 'MarkUnread', 'threadKeys': [{'otherUserFbId': '100010043825538'}]}}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=11&__rev=3328987&state=active&__req=p&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /pull?clientid=6c151adc&sticky_token=340&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=11&__rev=3328987&msgs_recv=0&__req=q&sticky_pool=atn1c09_chat-proxy HTTP/1.1" 200 169
DEBUG:client:Unknown message received: {'device_id': '950e76b8-412d-4f45-9650-d4467e3375b6', 'from': 100010043825538, 'st': 0, 'type': 't_tp', 'app_id': '256002347743983'}
DEBUG:urllib3.connectionpool:https://0-edge-chat.facebook.com:443 "GET /active_ping?channel=p_100022300173279&viewer_uid=100022300173279&uid=100022300173279&clientid=6c151adc&cap=0&partition=-2&__a=1&fb_dtsg=AQG1MK3Ucm0J%3AAQFE1ybvxS83&ttstamp=6581714977755185991094874586581706949121981181208356512&__user=100022300173279&seq=12&__rev=3328987&state=active&__req=r&sticky_pool=atn1c09_chat-proxy&sticky_token=340 HTTP/1.1" 200 22

**Comment by QuentinCG** [comment]
` FileNotFoundError: [Errno 2] No such file or directory: '/home/enzo/jarvis.sh'`

Shouldn't it be "/home/enzo/jarvis/jarvis.sh" ?

**Comment by Availleight** [comment]
Yes sorry for that ive fix it and now it works perfectly

**Comment by Availleight** [comment]
Thanks for all

**Comment by QuentinCG** [comment]
You are welcome
